# -*- coding: utf-8 -*-
"""embedd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YDwblvNnHen65nzLM3ByKBw1i-5JRB6
"""

import torch
import numpy as np
import pandas as pd
import json
from datetime import datetime, timezone
from pathlib import Path
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModel
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score
from scipy.sparse import csr_matrix, hstack

_ROOT = Path("/content/drive/MyDrive/Portafolio/HR Classfier")
CSV_PATH = _ROOT / "train_clean_validated.csv"
REPORT_PATH = _ROOT / "embedding_report.json"

print("1. Cargando Tokenizador y Modelo en modo 'Feature Extraction'...")
tokenizer = AutoTokenizer.from_pretrained("unitary/toxic-bert")
model = AutoModel.from_pretrained("unitary/toxic-bert")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Dispositivo configurado: {device}")

model = model.to(device)
model.eval()

df = pd.read_csv(CSV_PATH)
print(f"Total de filas a procesar: {len(df)}")

from torch.utils.data import Dataset, DataLoader
import torch

print("\n2. Extrayendo Embeddings con Aceleración Avanzada (DataLoader + Autocast)...")

class TextDataset(Dataset):
    def __init__(self, texts):
        self.texts = texts

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        return str(self.texts[idx])

text_list = df['comment_text'].tolist()
dataset = TextDataset(text_list)


batch_size_opt = 256
dataloader = DataLoader(dataset, batch_size=batch_size_opt, shuffle=False, num_workers=2, pin_memory=True)

all_embeddings = []

# 3. Bucle optimizado
for batch_texts in tqdm(dataloader):
    inputs = tokenizer(batch_texts, padding=True, truncation=True, max_length=512, return_tensors="pt")

    inputs = {k: v.to(device, non_blocking=True) for k, v in inputs.items()}

    with torch.no_grad():
        with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
            outputs = model(**inputs)

    cls_embeddings = outputs.last_hidden_state[:, 0, :]

    all_embeddings.append(cls_embeddings.cpu().numpy())

X_dense_transformer = np.vstack(all_embeddings)
print(f"Forma de los Embeddings: {X_dense_transformer.shape}")

print("\n3. Preparando etiquetas y Entrenando Regresión Logística...")

# 1. Unificar las etiquetas en una sola columna binaria 'is_toxic'
columnas_toxicas = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']
df['is_toxic'] = df[columnas_toxicas].max(axis=1)

# 2. Dividir los datos usando la nueva columna 'is_toxic'
X_train, X_test, y_train, y_test = train_test_split(
    X_dense_transformer,
    df['is_toxic'],
    test_size=0.2,
    random_state=42
)

# 3. Entrenar el modelo
log_reg = LogisticRegression(class_weight='balanced', max_iter=1000)
log_reg.fit(X_train, y_train)

print("¡Modelo entrenado exitosamente con Embeddings!")

print("\n4. Evaluando el modelo y generando el reporte JSON...")
y_pred = log_reg.predict(X_test)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

# Construir el JSON
report_data = {
  "meta": {
    "script": "embedd.ipynb",
    "timestamp": datetime.now(timezone.utc).isoformat(),
    "methodology": "toxic_bert_feature_extraction_binary",
    "model": "LogisticRegression(class_weight='balanced')"
  },
  "sample": {
    "total_extracted": len(df),
    "train_size": len(X_train),
    "test_size": len(X_test)
  },
  "confusion_matrix": {
    "true_negatives": int(tn),
    "false_positives": int(fp),
    "false_negatives": int(fn),
    "true_positives": int(tp)
  },
  "metrics": {
    "accuracy": round(accuracy_score(y_test, y_pred), 4),
    "precision": round(precision_score(y_test, y_pred, zero_division=0), 4),
    "recall": round(recall_score(y_test, y_pred, zero_division=0), 4),
    "f1_score": round(f1_score(y_test, y_pred, zero_division=0), 4)
  }
}

# Guardar
REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
with open(REPORT_PATH, 'w') as f:
    json.dump(report_data, f, indent=4)

print(f"¡Reporte generado y guardado exitosamente en: {REPORT_PATH}!")

print(df.columns.tolist())